# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downtime.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_downTimeDialog(object):
    def setupUi(self, downTimeDialog):
        downTimeDialog.setObjectName("downTimeDialog")
        downTimeDialog.resize(392, 271)
        self.verticalLayout = QtWidgets.QVBoxLayout(downTimeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(downTimeDialog)
        self.titleLabel.setAutoFillBackground(False)
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startLabel = QtWidgets.QLabel(downTimeDialog)
        self.startLabel.setObjectName("startLabel")
        self.horizontalLayout.addWidget(self.startLabel)
        self.startTimeEdit = QtWidgets.QTimeEdit(downTimeDialog)
        self.startTimeEdit.setObjectName("startTimeEdit")
        self.horizontalLayout.addWidget(self.startTimeEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.endLabel = QtWidgets.QLabel(downTimeDialog)
        self.endLabel.setObjectName("endLabel")
        self.horizontalLayout.addWidget(self.endLabel)
        self.endTimeEdit = QtWidgets.QTimeEdit(downTimeDialog)
        self.endTimeEdit.setObjectName("endTimeEdit")
        self.horizontalLayout.addWidget(self.endTimeEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resetTimeButton = QtWidgets.QPushButton(downTimeDialog)
        self.resetTimeButton.setObjectName("resetTimeButton")
        self.horizontalLayout_2.addWidget(self.resetTimeButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.applyTimeButton = QtWidgets.QPushButton(downTimeDialog)
        self.applyTimeButton.setObjectName("applyTimeButton")
        self.horizontalLayout_2.addWidget(self.applyTimeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(downTimeDialog)
        QtCore.QMetaObject.connectSlotsByName(downTimeDialog)

    def retranslateUi(self, downTimeDialog):
        _translate = QtCore.QCoreApplication.translate
        downTimeDialog.setWindowTitle(_translate("downTimeDialog", "Downtime"))
        self.titleLabel.setText(_translate("downTimeDialog", "Настройка времени сна"))
        self.startLabel.setText(_translate("downTimeDialog", "Старт:"))
        self.endLabel.setText(_translate("downTimeDialog", "Конец:"))
        self.resetTimeButton.setText(_translate("downTimeDialog", "Reset"))
        self.applyTimeButton.setText(_translate("downTimeDialog", "Apply"))
