# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downtime.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_downTimeDialog(object):
    def setupUi(self, downTimeDialog):
        downTimeDialog.setObjectName("downTimeDialog")
        downTimeDialog.resize(392, 271)
        self.verticalLayout = QtWidgets.QVBoxLayout(downTimeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(downTimeDialog)
        self.titleLabel.setAutoFillBackground(False)
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startLabel = QtWidgets.QLabel(downTimeDialog)
        self.startLabel.setObjectName("startLabel")
        self.horizontalLayout.addWidget(self.startLabel)
        self.startTimeEdit = QtWidgets.QTimeEdit(downTimeDialog)
        self.startTimeEdit.setObjectName("startTimeEdit")
        self.horizontalLayout.addWidget(self.startTimeEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.endLabel = QtWidgets.QLabel(downTimeDialog)
        self.endLabel.setObjectName("endLabel")
        self.horizontalLayout.addWidget(self.endLabel)
        self.endTimeEdit = QtWidgets.QTimeEdit(downTimeDialog)
        self.endTimeEdit.setObjectName("endTimeEdit")
        self.horizontalLayout.addWidget(self.endTimeEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.resetDownTimeButton = QtWidgets.QDialogButtonBox(downTimeDialog)
        self.resetDownTimeButton.setOrientation(QtCore.Qt.Horizontal)
        self.resetDownTimeButton.setStandardButtons(QtWidgets.QDialogButtonBox.Apply | QtWidgets.QDialogButtonBox.Reset)
        self.resetDownTimeButton.setObjectName("resetDownTimeButton")
        self.verticalLayout.addWidget(self.resetDownTimeButton)

        self.retranslateUi(downTimeDialog)
        self.resetDownTimeButton.accepted.connect(downTimeDialog.accept)  # type: ignore
        self.resetDownTimeButton.rejected.connect(downTimeDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(downTimeDialog)

    def retranslateUi(self, downTimeDialog):
        _translate = QtCore.QCoreApplication.translate
        downTimeDialog.setWindowTitle(_translate("downTimeDialog", "Downtime"))
        self.titleLabel.setText(_translate("downTimeDialog", "Настройка времени сна"))
        self.startLabel.setText(_translate("downTimeDialog", "Старт:"))
        self.endLabel.setText(_translate("downTimeDialog", "Конец:"))
